### ISSUE TITLE
A question about dataset

### ISSUE THREAD

**Issue by Yprimo** [exporl/locus-of-auditory-attention-cnn#1]
Hello,I'd like to know if the dataset provided is complete? I found that the data set did not correspond to the code. For example,do I need to extract the envelope myself? Do trials need to be split?

**Comment by svdc** [comment]
Apologies for the late reply. The dataset linked in the README was not correct unfortunately; I've updated it to refer to the correct dataset. I've also added the empty folders to the repo and extended the "Directory Structure" section to make it more clear where you should put the dataset.

It should be plug-and-play now. There's also no need to split your own trials, and this models does not use envelopes so there's no need to add them anywhere.

**Comment by servaasvdc** [comment]
Apologies for the late reply. The dataset linked in the README was not correct unfortunately; I've updated it to refer to the correct dataset. I've also added empty folders to the repo and extended the "Directory Structure" section to make it more clear where you should put the dataset.

It should be plug-and-play now. There's no need to split your own trials, and this models does not use envelopes so there's no need to add them anywhere.
